apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-slave
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-slave
  template:
    metadata:
      labels:
        app: jenkins-slave
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins-slave
          image: moelzedy/jenkins-slave-finalv
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
